media: assets
content:
  - name: global
    label: Global
    type: file
    path: content/global.json
    format: json
  - name: home
    label: Home
    type: file
    path: content/home.json
    format: json
  - name: about
    label: About
    type: file
    path: content/about.json
    format: json
  - name: work
    label: Work
    type: file
    path: content/work.json
    format: json
  - name: services
    label: Services
    type: file
    path: content/services.json
    format: json
  - name: products
    label: Products
    type: file
    path: content/products.json
    format: json
